Repository 5-PS/The-Julge, pull requests merged in 2024-04, with the labels that each got.

#11 setting: color palette 추가
  app/globals.css
  stories/.gitkeep
  tailwind.config.ts
Labels: FEATURE

#12 프로젝트 초기 세팅
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/settings.json
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/.gitkeep
  libs/axios.ts
  package-lock.json
  package.json
  public/fonts/.gitkeep
  public/icons/.gitkeep
  public/images/.gitkeep
  services/.gitkeep
  tailwind.config.ts
  tsconfig.json
  types/.gitkeep
  utils/.gitkeep
Labels: FEATURE

#13 setting: storybook tailwind 적용
  .storybook/main.ts
  .storybook/preview.ts
  components/button/button.stories.tsx
  components/button/button.tsx
  package.json
  postcss.config.js
  postcss.config.mjs
  tailwind.config.js
Labels: FEATURE

#14 setting: ESLint 설정 변경
  .eslintrc.json
  components/button/button.tsx
  package-lock.json
Labels: SETTING

#16 Feature/public button
  components/button/button.tsx
  public/images/modal-check.svg
  public/images/modal-issue.svg
  tailwind.config.js
Labels: FEATURE

#17 Feature/notification modal
  components/notificationModal/notificationBoard.tsx
  components/notificationModal/notificationCard.tsx
  package-lock.json
  package.json
  public/icons/close.svg
  tailwind.config.js
Labels: FEATURE

#18 Feature/table component
  .eslintrc.json
  app/globals.css
  components/pagination/pagination.tsx
  components/table/table.tsx
  public/icons/nexticon.svg
  public/icons/previcon.svg
  public/icons/previcondisabled.svg
Labels: FEATURE

#19 Feature/post
  components/post/post.tsx
  public/icons/arrow-gray.svg
  public/icons/arrow-red.svg
  public/icons/arrow-white.svg
  public/icons/clock-gray.svg
  public/icons/clock-red.svg
  public/icons/location-gray.svg
  public/icons/location-red.svg
  utils/calculatePercentage.ts
Labels: FEATURE

#21 Feature/input
  .eslintrc.json
  app/signin/_components/signinForm.tsx
  app/signin/page.tsx
  components/.gitkeep
  components/input/input.tsx
  tailwind.config.js
Labels: FEATURE

#23 rename: page-setting
  app/(auth)/signin/.gitkeep
  app/(auth)/signup/.gitkeep
  app/(service)/my-profile/.gitkeep
  app/(service)/my-profile/edit/.gitkeep
  app/(service)/my-store/edit/.gitkeep
  app/(service)/my-store/my-recruits/[recruitId]/.gitkeep
  app/(service)/my-store/my-recruits/edit/.gitkeep
  app/(service)/recruit-detail/.gitkeep
  app/(service)/recruit-detail/[recruitId]/.gitkeep
Labels: FEATURE

#20 feature: footer
  app/test/kye/page.tsx
  components/footer/footer.tsx
  public/icons/email.svg
  public/icons/facebook.svg
  public/icons/instagram.svg
Labels: FEATURE

#25 feature: select input
  app/globals.css
  components/input/selectInput.tsx
  public/icons/dropdown-down.svg
  public/icons/dropdown-top.svg
  tailwind.config.js
Labels: FEATURE

#22 feature: filter modal component
  app/globals.css
  components/filterModal/detailFilterModal.tsx
  package.json
  public/icons/close-modal-icon.svg
  public/icons/delete-label-icon.svg
Labels: FEATURE

#34 fix: 버튼 프롭 변경
  components/button/button.tsx
Labels: FIX

#30 feat: input (시급)
  app/(auth)/signin/_components/signinForm.tsx
  components/input/input.tsx
Labels: FEATURE, REFACTOR

#29 feature: gnb component
  app/layout.tsx
  app/page.tsx
  components/gnb/gnb.tsx
  components/gnb/notificationBtn.tsx
  components/gnb/searchBar.tsx
  public/icons/logo.svg
  public/icons/notification-active.svg
  public/icons/notification-inactive.svg
  public/icons/search.svg
Labels: FEATURE

#38 fix: select input 컴포넌트 수정
  components/input/selectInput.tsx
Labels: FIX

#35 fix: table 컴포넌트 동적 type 기능추가
  components/table/table.tsx
Labels: FIX

#36 feature: signup
  app/(auth)/layout.tsx
  app/(auth)/signup/.gitkeep
  app/(auth)/signup/_components/memberType.tsx
  app/(auth)/signup/_components/signupForm.tsx
  app/(auth)/signup/page.tsx
  public/icons/check.svg
  public/icons/main-logo.svg
  public/icons/not-check.svg
  services/.gitkeep
  services/api.ts
Labels: FEATURE

#41 refactor: pagination component refactor
  components/pagination/pagination.tsx
  utils/calculatePage.ts
Labels: REFACTOR

#43 fix: select input
  components/input/selectInput.tsx
Labels: FIX

#39 feature: SortingDropdown 컴포넌트 생성
  components/sortingDropdown/sortingDropdown.tsx
Labels: FEATURE

#55 feature: main page
  .vscode/settings.json
  app/_components/total.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/filterModal/detailFilterModal.tsx
  components/notificationModal/notificationCard.tsx
  components/post/post.tsx
  public/icons/arrow-red.svg
  public/icons/clock-red.svg
  public/icons/location-red.svg
  public/images/cat.jpg
Labels: FEATURE

#49 feature: my store edit form page
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  app/(service)/my-store/edit/page.tsx
  app/globals.css
  components/input/selectInput.tsx
  public/icons/image-add-icon.svg
Labels: FEATURE

#53 feature: my profile page
  app/(service)/layout.tsx
  app/(service)/my-profile/.gitkeep
  app/(service)/my-profile/page.tsx
  components/gnb/gnb.tsx
  public/icons/logo.svg
Labels: FEATURE

#57 fix: selectinput 에러처리 구현 및 적용
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  components/input/selectInput.tsx
Labels: FEATURE

#52 feature: recruit detail page
  app/(service)/recruit-detail/.gitkeep
  app/(service)/recruit-detail/[recruitId]/.gitkeep
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recentlyViewedRecruits.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/page.tsx
  components/post/percentageBadge.tsx
  package-lock.json
  utils/formatDateRange.ts
Labels: FEATURE

#33 feature: my recruits detail page
  app/(service)/my-store/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/my-recruits/[recruitId]/page.tsx
  app/globals.css
  components/pagination/pagination.tsx
  components/table/table.tsx
  package-lock.json
Labels: FEATURE

#58 refactor: signup
  app/(auth)/layout.tsx
  app/(auth)/signup/_components/memberType.tsx
  app/(auth)/signup/_components/signupForm.tsx
  app/(auth)/signup/page.tsx
  constants/route.ts
  public/icons/checked.svg
  public/icons/unchecked.svg
  services/api.ts
  types/api.ts
Labels: REFACTOR

#62 refactor: sorting dropdown fix
  components/sortingDropdown/sortingDropdown.tsx
  tailwind.config.js
Labels: REFACTOR

#63 feature: 로그인 시 쿠키에 jwt token 저장 기능 추가
  app/(auth)/signin/_components/signinForm.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/_components/signupForm.tsx
  constants/route.ts
Labels: FEATURE

#64 feature: my recruits edit 페이지 생성
  app/(service)/my-store/my-recruits/edit/.gitkeep
  app/(service)/my-store/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/my-store/my-recruits/edit/layout.tsx
  app/(service)/my-store/my-recruits/edit/page.tsx
Labels: FEATURE

#66 feature: table state badge component
  components/table/table.tsx
  components/tableStateBadge/applicationTableStateBadge.tsx
  components/tableStateBadge/applyTableStateBadge.tsx
  components/tableStateBadge/pendingBtn.tsx
Labels: FEATURE

#69 feature: jwt 유무 확인 함수 추가
  hooks/useCookieToken.ts
  utils/getCookieToken.ts
Labels: FEATURE

#71 feature: my store edit form
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  libs/axios.ts
  next.config.mjs
  services/api.ts
  types/api.ts
Labels: FEATURE

#72 feature: 로그인 시 직전 페이지로 이동 기능 추가
  app/(auth)/signin/_components/signinForm.tsx
  app/(auth)/signin/page.tsx
Labels: FEATURE

#74 feature: my profile edit page
  app/(service)/my-profile/[userId]/edit/.gitkeep
  app/(service)/my-profile/[userId]/edit/_components/profileEditForm.tsx
  app/(service)/my-profile/[userId]/edit/page.tsx
  services/api.ts
  types/api.ts
Labels: FEATURE

#75 feature: my store에 [storeId]추가 및 파일 이동
  app/(service)/my-store/[store-Id]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[store-Id]/_components/myStoreCard.tsx
  app/(service)/my-store/[store-Id]/_components/registeredNotice.tsx
  app/(service)/my-store/[store-Id]/_components/가게정보.json
  app/(service)/my-store/[store-Id]/_components/공고.json
  app/(service)/my-store/[store-Id]/edit/.gitkeep
  app/(service)/my-store/[store-Id]/edit/_components/myStoreForm.tsx
  app/(service)/my-store/[store-Id]/edit/page.tsx
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/.gitkeep
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/page.tsx
  app/(service)/my-store/[store-Id]/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/my-store/[store-Id]/my-recruits/edit/layout.tsx
  app/(service)/my-store/[store-Id]/my-recruits/edit/page.tsx
  app/(service)/my-store/[store-Id]/page.tsx
  app/(service)/my-store/_components/emptyStore.tsx
  app/(service)/my-store/page.tsx
  app/globals.css
  public/icons/cat.jpg
Labels: REFACTOR

#79 hotfix: hotfix postrequest axios instance
  app/(service)/my-profile/[userId]/edit/.gitkeep
  app/(service)/my-store/[store-Id]/edit/.gitkeep
  libs/axios.ts
  services/api.ts
  utils/getCookie.ts
Labels: FIX

#77 feature: post
  components/post/percentageBadge.tsx
  components/post/post.tsx
Labels: FEATURE

#80 refactor: my store 파일위치 수정
  app/(service)/my-store/[store-Id]/page.tsx
  app/(service)/my-store/_components/emptyStore.tsx
  app/(service)/my-store/edit/.gitkeep
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  app/(service)/my-store/edit/page.tsx
  app/(service)/my-store/page.tsx
Labels: REFACTOR

#85 feature: my recruit detail page 기능 구현
  app/(service)/my-profile/[userId]/edit/.gitkeep
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/_components/applicantList.tsx
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[store-Id]/my-recruits/[recruitId]/page.tsx
  components/pagination/pagination.tsx
  components/table/table.tsx
  components/tableStateBadge/applicationTableStateBadge.tsx
  components/tableStateBadge/pendingBtn.tsx
  services/api.ts
  types/api.ts
Labels: FEATURE

#87 feature: store modification form
  app/(service)/my-store/[store-Id]/edit/_components/myStoreForm.tsx
  app/(service)/my-store/[store-Id]/edit/page.tsx
  public/icons/image-change-icon.svg
  services/api.ts
Labels: FEATURE

#88 feature: toast
  app/(auth)/layout.tsx
  app/layout.tsx
  components/toast/toast.tsx
  contexts/providers.tsx
  contexts/toastContext.tsx
  hooks/useToast.ts
  public/icons/toast-close.svg
  tailwind.config.js
Labels: FEATURE

#89 feature: my store 서버데이터 받아와서 구성
  app/(service)/my-store/[store-Id]/_components/myStoreCard.tsx
  app/(service)/my-store/[store-Id]/edit/_components/myStoreForm.tsx
  app/(service)/my-store/[store-Id]/edit/page.tsx
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  app/(service)/my-store/[storeId]/_components/registeredNotice.tsx
  app/(service)/my-store/[storeId]/_components/가게정보.json
  app/(service)/my-store/[storeId]/_components/공고.json
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/.gitkeep
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/applicantList.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/page.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/layout.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/page.tsx
  app/(service)/my-store/[storeId]/page.tsx
  app/(service)/my-store/_components/emptyStore.tsx
  constants/route.ts
  services/api.ts
Labels: FEATURE

#92 feature: gnb component 검색 기능 및 알림 확인 기능
  app/(service)/_components/totalRecruitList.tsx
  components/filterModal/detailFilterModal.tsx
  components/gnb/authButton.tsx
  components/gnb/gnb.tsx
  components/gnb/notificationBtn.tsx
  components/gnb/searchBar.tsx
  components/notificationModal/notificationBoard.tsx
  components/notificationModal/notificationCard.tsx
  components/post/post.tsx
  services/api.ts
  types/api.ts
  types/notification.ts
  utils/decodeJWT.ts
Labels: FEATURE

#93 feature: middleware 및 유저 데이터를 받기 위한 custom hook 추가
  app/(auth)/layout.tsx
  constants/route.ts
  hooks/useUser.ts
  libs/axios.ts
  middleware.ts
  services/api.ts
  utils/decodeJWT.ts
Labels: FEATURE

#90 feature: 가게 공고 등록 Post기능 구현
  app/(service)/my-store/[storeId]/my-recruits/edit/_components/linkMyStore.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/page.tsx
  services/api.ts
  types/api.ts
Labels: FEATURE

#96 feature: middleware 조건 추가
  middleware.ts
Labels: FEATURE

#97 feature: gnb component function
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/applicantList.tsx
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  components/gnb/authButton.tsx
  libs/axios.ts
  utils/getCookie.ts
Labels: FEATURE

#95 feature: recruit detail page
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/applicationButton.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recentlyViewedRecruits.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/page.tsx
  services/api.ts
  utils/formatDateRange.ts
Labels: FEATURE

#100 feat: 가게 수정 폼 재생성
  app/(service)/my-store/[storeId]/edit/_components/myStoreModificationForm.tsx
  app/(service)/my-store/[storeId]/edit/page.tsx
Labels: FEATURE

#99 feature: my-store/[storeId] api연결
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  app/(service)/my-store/[storeId]/_components/registeredNotice.tsx
  app/(service)/my-store/[storeId]/page.tsx
  services/api.ts
Labels: FEATURE

#102 hotfix: 헤더 및 페이지 수정
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/page.tsx
  components/gnb/authButton.tsx
Labels: FIX

#103 fix: sign in previous page
  app/(auth)/signin/_components/signinForm.tsx
  app/(auth)/signin/page.tsx
Labels: FIX

#105 fix: 타입 에러 수정
  .storybook/main.ts
  .storybook/preview.ts
  app/(service)/_components/totalRecruitList.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recentlyViewedRecruits.tsx
  components/button/button.stories.tsx
  components/filterModal/detailFilterModal.tsx
  components/post/post.tsx
  types/api.ts
Labels: FIX

#106 chore: eslint 설정 일부 비활성화
  .eslintrc.json
Labels: SETTING

#112 feature: loading UI 추가
  app/(service)/loading.tsx
  public/icons/loading.svg
Labels: FEATURE

#113 feature: modal
  app/layout.tsx
  components/modal/cautionModal.tsx
  components/modal/checkModal.tsx
  components/modal/modalContainer.tsx
  components/modal/noticeModal.tsx
  contexts/ModalProvider.tsx
  hooks/useModal.tsx
  hooks/useOutSideClick.ts
  package-lock.json
  public/icons/modal-issue.svg
Labels: FEATURE

#114 feature: 무한 스크롤 구현
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  services/api.ts
Labels: FEATURE

#115 feature: recruit detail page
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/applicationButton.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recentlyViewedRecruits.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/page.tsx
  components/modal/cautionModal.tsx
  components/modal/checkModal.tsx
  components/modal/modalContainer.tsx
  components/modal/noticeModal.tsx
  components/post/post.tsx
  hooks/useRecruitActions.ts
  middleware.ts
  services/api.ts
Labels: FEATURE

#117 fix: post
  app/(service)/_components/personal.tsx
  app/(service)/_components/totalRecruitList.tsx
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recentlyViewedRecruits.tsx
  components/post/post.tsx
Labels: FIX

#116 fix: modal
  components/modal/cautionModal.tsx
  components/modal/checkModal.tsx
  components/modal/noticeModal.tsx
Labels: FIX

#119 fix: 데이터 받는 방법 수정
  app/(service)/_components/personal.tsx
  app/(service)/page.tsx
  components/gnb/authButton.tsx
Labels: FIX

#120 design: footer 위치 조정
  app/(service)/my-store/page.tsx
  app/(service)/page.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/page.tsx
  app/layout.tsx
  components/footer/footer.tsx
Labels: FIX

#121 feature: 로그인 및 회원가입 페이지 모달 기능 추가
  app/(auth)/signin/_components/signinForm.tsx
  app/(auth)/signup/_components/signupForm.tsx
Labels: FEATURE

#122 feature: my recruits edit
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/layout.tsx
  app/layout.tsx
  components/modal/cautionModal.tsx
Labels: FEATURE

#123 fix 자잘한 css 수정 및 내프로필편집 default values 설정
  app/(service)/my-profile/[userId]/_components/applyList.tsx
  app/(service)/my-profile/[userId]/_components/empty.tsx
  app/(service)/my-profile/[userId]/_components/profileContainer.tsx
  app/(service)/my-profile/[userId]/edit/_components/profileEditForm.tsx
  components/pagination/pagination.tsx
  services/api.ts
  types/api.ts
Labels: FIX, REFACTOR

#124 fix: my recruits page modal
  app/(service)/my-store/[storeId]/edit/_components/myStoreModificationForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/.gitkeep
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/edit/.gitkeep
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  app/layout.tsx
  components/tableStateBadge/pendingBtn.tsx
  public/images/favicon.ico
Labels: FIX

#127 fix: recruit detail page
  app/(service)/_components/personal.tsx
  app/(service)/my-profile/[userId]/_components/profileContainer.tsx
  app/(service)/my-profile/[userId]/edit/_components/profileEditForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/edit/_components/registRecruitForm.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/applicationButton.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  components/gnb/authButton.tsx
  components/post/post.tsx
  hooks/useRecruitActions.ts
  hooks/useUser.ts
  services/api.ts
Labels: FIX

#126 Feature/my recruits edit
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[storeId]/edit/page.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/edit/_components/closeButton.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/edit/_components/recruitEdit.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/edit/page.tsx
  services/api.ts
  types/api.ts
Labels: FEATURE

#129 fix: 프로필 수정 폼 모달 적용
  app/(service)/my-profile/[userId]/edit/.gitkeep
  app/(service)/my-profile/[userId]/edit/_components/profileEditForm.tsx
  app/(service)/my-profile/[userId]/edit/page.tsx
Labels: FIX

#132 design: sorting dropdown 스타일 수정
  app/(service)/my-profile/[userId]/_components/profileContainer.tsx
  app/(service)/my-store/[storeId]/_components/haveRegisteredNotice.tsx
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  app/(service)/my-store/[storeId]/_components/가게정보.json
  app/(service)/my-store/[storeId]/_components/공고.json
  app/(service)/my-store/[storeId]/edit/_components/myStoreModificationForm.tsx
  app/(service)/my-store/[storeId]/edit/page.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/edit/page.tsx
  app/(service)/my-store/[storeId]/page.tsx
  app/(service)/my-store/_components/emptyStore.tsx
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  app/(service)/my-store/edit/page.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  components/gnb/authButton.tsx
  components/gnb/searchBar.tsx
  components/sortingDropdown/sortingDropdown.tsx
  components/table/table.tsx
  package.json
Labels: FIX

#136 feature/fix css
  app/(service)/_components/personal.tsx
  app/(service)/_components/totalRecruitList.tsx
  app/(service)/my-store/[storeId]/_components/myStoreCard.tsx
  app/(service)/my-store/[storeId]/edit/_components/myStoreModificationForm.tsx
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/recruitsCard.tsx
  app/(service)/my-store/edit/_components/myStoreForm.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/applicationButton.tsx
  app/(service)/recruit-detail/[shopId]/[recruitId]/_components/recruitCard.tsx
  components/input/selectInput.tsx
  components/sortingDropdown/sortingDropdown.tsx
Labels: FIX

#135 feature: popOver
  components/filterModal/detailFilterModal.tsx
  components/gnb/notificationBtn.tsx
  components/notificationModal/notificationBoard.tsx
  components/sortingDropdown/sortingDropdown.tsx
  hooks/useOutSideClick.ts
  types/.gitkeep
  utils/.gitkeep
Labels: FEATURE

#138 fix: pc버전 테이블 design 수정
  components/table/table.tsx
Labels: FIX

#140 feat: 승인시 모두 거절 기능 구현
  app/(service)/my-store/[storeId]/my-recruits/[recruitId]/_components/applicantList.tsx
Labels: FIX
